// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6OZxuCpwhZt4ZrsPBj3L9ZnucmhPJFc',
    appId: '1:93538098342:web:7dea6fb70fdd508738a867',
    messagingSenderId: '93538098342',
    projectId: 'ramen-music-player',
    authDomain: 'ramen-music-player.firebaseapp.com',
    storageBucket: 'ramen-music-player.appspot.com',
    measurementId: 'G-CTSWEQ081W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvnLrCPj-U06UFkZZweGPWzcUKbb9Qsg',
    appId: '1:93538098342:android:253f0db9f1ac4b0338a867',
    messagingSenderId: '93538098342',
    projectId: 'ramen-music-player',
    storageBucket: 'ramen-music-player.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6uR5EboXCuFz3m0pkGwsR5RfQLwDGAo',
    appId: '1:93538098342:ios:09792c2bc83ef5c438a867',
    messagingSenderId: '93538098342',
    projectId: 'ramen-music-player',
    storageBucket: 'ramen-music-player.appspot.com',
    iosClientId: '93538098342-s99mvtnqe13i9rdc5p6207e65amqv0n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramenMusicPlayer',
  );
}
